'use strict';
window.MA = window.MA || {};
window.MA.modules = window.MA.modules || {};

window.MA.modules.gantt = (function() {
  // ── Constants ──
  var STATUS_KEYWORDS = ['done', 'active', 'crit', 'milestone'];
  var DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
  var DURATION_RE = /^\d+[dwmyhMs]$/;

  // ── Helpers ──
  function isDate(s) { return DATE_RE.test(s); }
  function isDuration(s) { return DURATION_RE.test(s); }
  function isAfter(s) { return typeof s === 'string' && s.indexOf('after ') === 0; }

  // parseTaskLine — parses a single raw task line into its components.
  // Returns null if the line doesn't look like a task (no colon).
  function parseTaskLine(line) {
    var trimmed = line.trim();
    var colonIdx = trimmed.indexOf(':');
    if (colonIdx === -1) return null;

    var label = trimmed.slice(0, colonIdx).trim();
    var metaStr = trimmed.slice(colonIdx + 1).trim();
    var parts = metaStr.split(',').map(function(s) { return s.trim(); });

    var status = null;
    var id = null;
    var startDate = null;
    var endDate = null;
    var after = null;
    var idx = 0;

    // Detect leading whitespace (indent)
    var indent = '';
    var m = line.match(/^(\s*)/);
    if (m) indent = m[1];

    // status keyword?
    if (idx < parts.length && STATUS_KEYWORDS.indexOf(parts[idx]) !== -1) {
      status = parts[idx];
      idx++;
    }

    // 'after' at start position?
    var afterMatch = null;
    if (idx < parts.length && parts[idx].indexOf('after ') === 0) {
      afterMatch = parts[idx].slice('after '.length).trim();
      idx++;
    } else {
      // id or date/duration?
      if (idx < parts.length) {
        var candidate = parts[idx];
        if (!isDate(candidate) && !isDuration(candidate) && candidate.indexOf('after ') !== 0) {
          id = candidate;
          idx++;
        }
      }
      // 'after' after id?
      if (idx < parts.length && parts[idx].indexOf('after ') === 0) {
        afterMatch = parts[idx].slice('after '.length).trim();
        idx++;
      }
    }

    if (afterMatch !== null) {
      after = afterMatch;
      if (idx < parts.length) { endDate = parts[idx]; idx++; }
    } else {
      if (idx < parts.length) { startDate = parts[idx]; idx++; }
      if (idx < parts.length) { endDate = parts[idx]; idx++; }
    }

    return { label: label, indent: indent, status: status, id: id, startDate: startDate, endDate: endDate, after: after };
  }

  // rebuildTaskMeta — reconstructs the `:metadata` portion from components.
  // Omits __auto_ IDs (they are generated by the parser for tasks that had no id).
  function rebuildTaskMeta(status, id, startDate, endDate, after) {
    var parts = [];
    if (status) parts.push(status);
    if (id && !window.MA.parserUtils.isAutoId(id)) parts.push(id);
    if (after && !startDate) {
      parts.push('after ' + after);
    } else if (startDate) {
      parts.push(startDate);
    }
    if (endDate) parts.push(endDate);
    return parts.join(', ');
  }

  // parseGantt — pure function: text → ParsedData
  // ParsedData = {
  //   title: string,
  //   dateFormat: string,
  //   axisFormat: string,
  //   sections: [{ name: string, line: number }],
  //   tasks: [{
  //     id: string, label: string, status: string|null,
  //     startDate: string|null, endDate: string|null,
  //     after: string|null, line: number, sectionIndex: number
  //   }]
  // }
  function parseGantt(text) {
    var result = {
      title: '',
      dateFormat: 'YYYY-MM-DD',
      axisFormat: '',
      sections: [],
      tasks: [],
    };

    if (!text || !text.trim()) {
      return result;
    }

    var lines = text.split('\n');
    var autoIdCounter = 0;
    var currentSectionIndex = -1;

    for (var i = 0; i < lines.length; i++) {
      var lineNum = i + 1;  // 1-based
      var raw = lines[i];
      var trimmed = raw.trim();

      // Skip empty lines, 'gantt' keyword, and comments
      if (!trimmed || trimmed === 'gantt' || trimmed.indexOf('%%') === 0) {
        continue;
      }

      // Directives we acknowledge but don't store
      if (trimmed.indexOf('excludes') === 0 || trimmed.indexOf('todayMarker') === 0) {
        continue;
      }

      // title
      if (trimmed.indexOf('title ') === 0) {
        result.title = trimmed.slice('title '.length).trim();
        continue;
      }

      // dateFormat
      if (trimmed.indexOf('dateFormat ') === 0) {
        result.dateFormat = trimmed.slice('dateFormat '.length).trim();
        continue;
      }

      // axisFormat
      if (trimmed.indexOf('axisFormat ') === 0) {
        result.axisFormat = trimmed.slice('axisFormat '.length).trim();
        continue;
      }

      // section
      if (trimmed.indexOf('section ') === 0) {
        var sectionName = trimmed.slice('section '.length).trim();
        result.sections.push({ name: sectionName, line: lineNum });
        currentSectionIndex = result.sections.length - 1;
        continue;
      }

      // Task line — must contain ':'
      if (trimmed.indexOf(':') === -1) {
        continue;
      }

      var p = parseTaskLine(raw);
      if (!p) continue;

      // Auto-generate id if not set
      var taskId = p.id !== null ? p.id : window.MA.parserUtils.generateAutoId('auto', autoIdCounter++);

      result.tasks.push({
        id: taskId,
        label: p.label,
        status: p.status,
        startDate: p.startDate,
        endDate: p.endDate,
        after: p.after,
        line: lineNum,
        sectionIndex: currentSectionIndex,
      });
    }

    return result;
  }

  // updateTaskDates — replaces dates on the line at 1-based lineNum.
  // Pass null for newStart or newEnd to leave that value unchanged.
  // When newStart is provided, any 'after' dependency is cleared.
  function updateTaskDates(text, lineNum, newStart, newEnd) {
    var lines = text.split('\n');
    var idx = lineNum - 1;
    if (idx < 0 || idx >= lines.length) return text;

    var parsed = parseTaskLine(lines[idx]);
    if (!parsed) return text;

    var start = newStart !== null && newStart !== undefined ? newStart : parsed.startDate;
    var end   = newEnd   !== null && newEnd   !== undefined ? newEnd   : parsed.endDate;
    // If a new start is given, clear 'after' dependency
    var after = (newStart !== null && newStart !== undefined) ? null : parsed.after;

    var meta = rebuildTaskMeta(parsed.status, parsed.id, start, end, after);
    lines[idx] = parsed.indent + parsed.label + ' :' + meta;
    return lines.join('\n');
  }

  // updateTaskField — updates label, status, or id on the line at 1-based lineNum.
  // Pass null to remove status.
  function updateTaskField(text, lineNum, field, value) {
    var lines = text.split('\n');
    var idx = lineNum - 1;
    if (idx < 0 || idx >= lines.length) return text;

    var parsed = parseTaskLine(lines[idx]);
    if (!parsed) return text;

    if (field === 'label') {
      parsed.label = value;
    } else if (field === 'status') {
      parsed.status = value || null;
    } else if (field === 'id') {
      parsed.id = value;
    } else if (field === 'after') {
      if (value && value.trim()) {
        parsed.after = value.trim();
        parsed.startDate = null; // after指定時はstartDateをクリア
      } else {
        parsed.after = null;
      }
    }

    var meta = rebuildTaskMeta(parsed.status, parsed.id, parsed.startDate, parsed.endDate, parsed.after);
    lines[idx] = parsed.indent + parsed.label + ' :' + meta;
    return lines.join('\n');
  }

  // addTask — inserts a new task line at the end of the section identified by
  // sectionIndex (0-based, from parseGantt result). Pass -1 to append at end of
  // the whole diagram.
  function addTask(text, sectionIndex, label, id, startDate, endDate) {
    var lines = text.split('\n');
    var parsed = parseGantt(text);
    var newLine = '    ' + label + ' :' + rebuildTaskMeta(null, id, startDate, endDate, null);

    var insertAt; // index in lines array AFTER which we insert (we splice at insertAt+1)

    if (sectionIndex === -1 || parsed.sections.length === 0) {
      // Append at end of file (trim trailing empty lines to keep it tidy)
      insertAt = lines.length - 1;
      // Back up past trailing empty lines
      while (insertAt > 0 && lines[insertAt].trim() === '') insertAt--;
      lines.splice(insertAt + 1, 0, newLine);
      return lines.join('\n');
    }

    // Find the last task line that belongs to this section, or fall back to the
    // section header line itself.
    var sectionLine = parsed.sections[sectionIndex].line; // 1-based
    var lastLineInSection = sectionLine; // 1-based, will advance

    // The next section starts at…
    var nextSectionLine = parsed.sections.length > sectionIndex + 1
      ? parsed.sections[sectionIndex + 1].line  // 1-based
      : lines.length + 1;                        // sentinel beyond end

    // Walk tasks to find the last one in this section
    for (var i = 0; i < parsed.tasks.length; i++) {
      if (parsed.tasks[i].sectionIndex === sectionIndex) {
        if (parsed.tasks[i].line > lastLineInSection) {
          lastLineInSection = parsed.tasks[i].line;
        }
      }
    }

    // Make sure we don't overshoot into the next section
    if (lastLineInSection >= nextSectionLine) {
      lastLineInSection = nextSectionLine - 1;
    }

    // Insert after lastLineInSection (convert to 0-based index)
    lines.splice(lastLineInSection, 0, newLine); // splice(lastLineInSection, 0, ...) inserts AFTER that index (0-based = 1-based - 1 + 1)
    return lines.join('\n');
  }

  // deleteTask — removes the line at 1-based lineNum.
  function deleteTask(text, lineNum) {
    return window.MA.textUpdater.deleteLine(text, lineNum);
  }

  // sanitizeAfterDependencies — adjusts dependent task end dates to maintain validity.
  function sanitizeAfterDependencies(text) {
    var p = parseGantt(text);
    var lines = text.split('\n');
    var changed = false;

    for (var i = 0; i < p.tasks.length; i++) {
      var t = p.tasks[i];
      if (!t.after) continue;

      // Find the referenced task
      var ref = null;
      for (var j = 0; j < p.tasks.length; j++) {
        if (p.tasks[j].id === t.after) { ref = p.tasks[j]; break; }
      }
      if (!ref) continue;

      // Resolve the referenced task's end date
      var refEnd = ref.endDate;
      if (!refEnd || !DATE_RE.test(refEnd)) continue;

      // Check if this task's end date is before the ref's end date
      if (t.endDate && DATE_RE.test(t.endDate)) {
        if (window.MA.dateUtils.daysBetween(refEnd, t.endDate) < 1) {
          // Push end date to refEnd + 1 day
          var newEnd = window.MA.dateUtils.addDays(refEnd, 1);
          var parsed = parseTaskLine(lines[t.line - 1]);
          if (parsed) {
            var meta = rebuildTaskMeta(parsed.status, parsed.id, parsed.startDate, newEnd, parsed.after);
            lines[t.line - 1] = parsed.indent + parsed.label + ' :' + meta;
            changed = true;
          }
        }
      }
    }

    return changed ? lines.join('\n') : text;
  }

  // addSection — appends a new section at the end of the diagram.
  function addSection(text, name) {
    var lines = text.split('\n');
    // Append at end (before trailing empty lines)
    var insertIdx = lines.length;
    while (insertIdx > 0 && lines[insertIdx - 1].trim() === '') insertIdx--;
    lines.splice(insertIdx, 0, '', '    section ' + name);
    return lines.join('\n');
  }

  // deleteSection — removes the section and all its tasks.
  function deleteSection(text, sectionLine) {
    var lines = text.split('\n');
    var p = parseGantt(text);
    var secIdx = -1;
    for (var i = 0; i < p.sections.length; i++) {
      if (p.sections[i].line === sectionLine) { secIdx = i; break; }
    }
    if (secIdx === -1) return text;
    // Find range: from section line to next section (or end)
    var startIdx = sectionLine - 1;
    var endIdx;
    if (secIdx + 1 < p.sections.length) {
      endIdx = p.sections[secIdx + 1].line - 1;
    } else {
      endIdx = lines.length;
    }
    // Remove blank line before section if present
    if (startIdx > 0 && lines[startIdx - 1].trim() === '') startIdx--;
    lines.splice(startIdx, endIdx - startIdx);
    return lines.join('\n');
  }

  // updateGlobalSetting — updates or inserts a global directive (title, dateFormat, axisFormat).
  function updateGlobalSetting(text, key, value) {
    var lines = text.split('\n');
    var found = false;
    for (var i = 0; i < lines.length; i++) {
      if (lines[i].trim().indexOf(key + ' ') === 0) {
        lines[i] = '    ' + key + ' ' + value;
        found = true;
        break;
      }
    }
    if (!found) {
      // Insert after 'gantt' line
      for (var j = 0; j < lines.length; j++) {
        if (lines[j].trim() === 'gantt') {
          lines.splice(j + 1, 0, '    ' + key + ' ' + value);
          break;
        }
      }
    }
    return lines.join('\n');
  }

  // moveTaskWithinSection — moves the task at 1-based lineNum up (-1) or down (+1)
  // within its current section.
  function moveTaskWithinSection(text, lineNum, direction) {
    if (direction !== -1 && direction !== 1) return text;
    var p = parseGantt(text);
    var task = null;
    for (var i = 0; i < p.tasks.length; i++) {
      if (p.tasks[i].line === lineNum) { task = p.tasks[i]; break; }
    }
    if (!task) return text;

    // Tasks in the same section, sorted by line
    var siblings = p.tasks.filter(function(t) { return t.sectionIndex === task.sectionIndex; });
    siblings.sort(function(a, b) { return a.line - b.line; });
    var idx = -1;
    for (var si = 0; si < siblings.length; si++) {
      if (siblings[si].line === lineNum) { idx = si; break; }
    }
    if (idx === -1) return text;

    var swapIdx = idx + direction;
    if (swapIdx < 0 || swapIdx >= siblings.length) return text; // boundary

    return window.MA.textUpdater.swapLines(text, lineNum, siblings[swapIdx].line);
  }

  // moveTaskToSection — moves the task at 1-based lineNum to the end of the
  // section identified by targetSectionIndex (0-based).
  function moveTaskToSection(text, lineNum, targetSectionIndex) {
    var p = parseGantt(text);
    var task = null;
    for (var i = 0; i < p.tasks.length; i++) {
      if (p.tasks[i].line === lineNum) { task = p.tasks[i]; break; }
    }
    if (!task) return text;
    if (task.sectionIndex === targetSectionIndex) return text; // already there
    if (targetSectionIndex < -1 || targetSectionIndex >= p.sections.length) return text;

    // Capture the original task line content
    var lines = text.split('\n');
    var taskLineContent = lines[lineNum - 1];

    // Delete the original line first
    var afterDelete = deleteTask(text, lineNum);

    // Re-parse the post-delete state and find the insertion point at the target section
    var p2 = parseGantt(afterDelete);
    var lines2 = afterDelete.split('\n');
    var insertAt;

    if (targetSectionIndex === -1 || p2.sections.length === 0) {
      // Append at end (trim trailing empty lines)
      insertAt = lines2.length;
      while (insertAt > 0 && lines2[insertAt - 1].trim() === '') insertAt--;
    } else {
      var sectionLine = p2.sections[targetSectionIndex].line; // 1-based
      var nextSectionLine = (targetSectionIndex + 1 < p2.sections.length)
        ? p2.sections[targetSectionIndex + 1].line
        : lines2.length + 1;
      var lastLineInSection = sectionLine;
      for (var ti = 0; ti < p2.tasks.length; ti++) {
        if (p2.tasks[ti].sectionIndex === targetSectionIndex && p2.tasks[ti].line > lastLineInSection) {
          lastLineInSection = p2.tasks[ti].line;
        }
      }
      if (lastLineInSection >= nextSectionLine) lastLineInSection = nextSectionLine - 1;
      insertAt = lastLineInSection; // 0-based: insert at this index = after lastLineInSection (1-based)
    }

    lines2.splice(insertAt, 0, taskLineContent);
    return lines2.join('\n');
  }

  // ── Calibration (ADR-010) ─────────────────────────────────────────────────
  var calibration = { pxPerDay: 0, originX: 0, baseDate: '', barRects: [] };

  function calibrateScale(svgEl, parsedData) {
    calibration = { pxPerDay: 0, originX: 0, baseDate: '', barRects: [] };
    if (!svgEl || !parsedData || !parsedData.tasks || parsedData.tasks.length === 0) return;

    // ── Match tasks to SVG rects via text label y-position proximity ──
    // Step 1: Collect all text elements and their y-centers
    var textEls = svgEl.querySelectorAll('text');
    var labelInfos = []; // {text, yCenter}
    for (var ti2 = 0; ti2 < textEls.length; ti2++) {
      try {
        var tbb = textEls[ti2].getBBox();
        labelInfos.push({ text: textEls[ti2].textContent.trim(), yCenter: tbb.y + tbb.height / 2 });
      } catch (e) { /* skip */ }
    }

    // Step 2: Collect candidate bar rects (reasonable size, not full-width backgrounds)
    var vb = svgEl.viewBox.baseVal;
    var chartWidth = vb ? vb.width : 2000;
    var allRects = svgEl.querySelectorAll('rect');
    var candidateRects = []; // {x, y, width, height, yCenter}
    for (var cri = 0; cri < allRects.length; cri++) {
      try {
        var rbb = allRects[cri].getBBox();
        // Task bars: reasonable height (8-40px), not too wide (< 95% of chart), minimum width
        if (rbb.height >= 8 && rbb.height <= 40 && rbb.width >= 3 && rbb.width < chartWidth * 0.95) {
          candidateRects.push({ x: rbb.x, y: rbb.y, width: rbb.width, height: rbb.height, yCenter: rbb.y + rbb.height / 2, used: false });
        }
      } catch (e) { /* skip */ }
    }

    // Step 3: For each task, find its text label, then find the closest candidate rect
    var barRects = []; // one per task (or null)
    for (var ti = 0; ti < parsedData.tasks.length; ti++) {
      var task = parsedData.tasks[ti];
      var taskLabel = task.label.trim();

      // Find matching text label
      var labelY = null;
      for (var li = 0; li < labelInfos.length; li++) {
        if (labelInfos[li].text === taskLabel) {
          labelY = labelInfos[li].yCenter;
          labelInfos.splice(li, 1); // consume it so duplicate labels map to different rects
          break;
        }
      }

      if (labelY === null) {
        barRects.push(null);
        continue;
      }

      // Find closest unused candidate rect by y-center
      var closest = null;
      var closestDist = Infinity;
      for (var ri = 0; ri < candidateRects.length; ri++) {
        if (candidateRects[ri].used) continue;
        var dist = Math.abs(candidateRects[ri].yCenter - labelY);
        if (dist < closestDist) {
          closestDist = dist;
          closest = ri;
        }
      }

      if (closest !== null && closestDist < 30) {
        candidateRects[closest].used = true;
        var cr = candidateRects[closest];
        barRects.push({ x: cr.x, y: cr.y, width: cr.width, height: cr.height });
      } else {
        barRects.push(null);
      }
    }
    calibration.barRects = barRects;

    // ── Calibrate pxPerDay from tasks with known dates ──
    var calibrated = false;
    var tasksWithDates = [];
    for (var di = 0; di < parsedData.tasks.length; di++) {
      if (parsedData.tasks[di].startDate && DATE_RE.test(parsedData.tasks[di].startDate) && barRects[di]) {
        tasksWithDates.push({ task: parsedData.tasks[di], rect: barRects[di] });
      }
    }

    // Two-task calibration
    for (var ci = 0; ci < tasksWithDates.length && !calibrated; ci++) {
      for (var cj = ci + 1; cj < tasksWithDates.length && !calibrated; cj++) {
        var t1 = tasksWithDates[ci], t2 = tasksWithDates[cj];
        if (t1.task.startDate === t2.task.startDate) continue;
        var dDays = window.MA.dateUtils.daysBetween(t1.task.startDate, t2.task.startDate);
        if (dDays === 0) continue;
        calibration.pxPerDay = (t2.rect.x - t1.rect.x) / dDays;
        calibration.originX = t1.rect.x;
        calibration.baseDate = t1.task.startDate;
        calibrated = true;
      }
    }

    // Single-task fallback
    if (!calibrated && tasksWithDates.length >= 1) {
      var st = tasksWithDates[0];
      if (st.task.endDate && DATE_RE.test(st.task.endDate)) {
        var dur = window.MA.dateUtils.daysBetween(st.task.startDate, st.task.endDate);
        if (dur > 0) {
          calibration.pxPerDay = st.rect.width / dur;
          calibration.originX = st.rect.x;
          calibration.baseDate = st.task.startDate;
        }
      }
    }
  }

  function pxToDate(px) {
    if (calibration.pxPerDay === 0) return null;
    var daysDelta = Math.round((px - calibration.originX) / calibration.pxPerDay);
    return window.MA.dateUtils.addDays(calibration.baseDate, daysDelta);
  }

  function dateToPx(dateStr) {
    if (calibration.pxPerDay === 0) return 0;
    return calibration.originX + window.MA.dateUtils.daysBetween(calibration.baseDate, dateStr) * calibration.pxPerDay;
  }

  // ── Module export ──
  return {
    type: 'gantt',
    displayName: 'Gantt',
    detect: function(text) { return text.trim().startsWith('gantt'); },
    parse: parseGantt,
    template: function() {
      return [
        'gantt',
        '    title プロジェクト計画',
        '    dateFormat YYYY-MM-DD',
        '    axisFormat %m/%d',
        '',
        '    section 要件定義',
        '    要件分析           :a1, 2026-04-01, 2026-04-15',
      ].join('\n');
    },
    // Public API for use by app.js (until full DiagramModule v2 abstraction)
    parseGantt: parseGantt,
    parseTaskLine: parseTaskLine,
    rebuildTaskMeta: rebuildTaskMeta,
    updateTaskDates: updateTaskDates,
    updateTaskField: updateTaskField,
    addTask: addTask,
    deleteTask: deleteTask,
    sanitizeAfterDependencies: sanitizeAfterDependencies,
    addSection: addSection,
    deleteSection: deleteSection,
    updateGlobalSetting: updateGlobalSetting,
    moveTaskWithinSection: moveTaskWithinSection,
    moveTaskToSection: moveTaskToSection,
    calibrateScale: calibrateScale,
    pxToDate: pxToDate,
    dateToPx: dateToPx,
    getCalibration: function() { return calibration; },
    setCalibration: function(c) { calibration = c; },
    DATE_RE: DATE_RE,
    DURATION_RE: DURATION_RE,
    STATUS_KEYWORDS: STATUS_KEYWORDS,
  };
})();
