'use strict';
window.MA = window.MA || {};
window.MA.modules = window.MA.modules || {};

window.MA.modules.gantt = (function() {
  // ── Constants ──
  var STATUS_KEYWORDS = ['done', 'active', 'crit', 'milestone'];
  var DATE_RE = /^\d{4}-\d{2}-\d{2}$/;
  var DURATION_RE = /^\d+[dwmyhMs]$/;

  // ── Helpers ──
  function isDate(s) { return DATE_RE.test(s); }
  function isDuration(s) { return DURATION_RE.test(s); }
  function isAfter(s) { return typeof s === 'string' && s.indexOf('after ') === 0; }

  // parseTaskLine — parses a single raw task line into its components.
  // Returns null if the line doesn't look like a task (no colon).
  function parseTaskLine(line) {
    var trimmed = line.trim();
    var colonIdx = trimmed.indexOf(':');
    if (colonIdx === -1) return null;

    var label = trimmed.slice(0, colonIdx).trim();
    var metaStr = trimmed.slice(colonIdx + 1).trim();
    var parts = metaStr.split(',').map(function(s) { return s.trim(); });

    var status = null;
    var id = null;
    var startDate = null;
    var endDate = null;
    var after = null;
    var idx = 0;

    // Detect leading whitespace (indent)
    var indent = '';
    var m = line.match(/^(\s*)/);
    if (m) indent = m[1];

    // status keyword?
    if (idx < parts.length && STATUS_KEYWORDS.indexOf(parts[idx]) !== -1) {
      status = parts[idx];
      idx++;
    }

    // 'after' at start position?
    var afterMatch = null;
    if (idx < parts.length && parts[idx].indexOf('after ') === 0) {
      afterMatch = parts[idx].slice('after '.length).trim();
      idx++;
    } else {
      // id or date/duration?
      if (idx < parts.length) {
        var candidate = parts[idx];
        if (!isDate(candidate) && !isDuration(candidate) && candidate.indexOf('after ') !== 0) {
          id = candidate;
          idx++;
        }
      }
      // 'after' after id?
      if (idx < parts.length && parts[idx].indexOf('after ') === 0) {
        afterMatch = parts[idx].slice('after '.length).trim();
        idx++;
      }
    }

    if (afterMatch !== null) {
      after = afterMatch;
      if (idx < parts.length) { endDate = parts[idx]; idx++; }
    } else {
      if (idx < parts.length) { startDate = parts[idx]; idx++; }
      if (idx < parts.length) { endDate = parts[idx]; idx++; }
    }

    return { label: label, indent: indent, status: status, id: id, startDate: startDate, endDate: endDate, after: after };
  }

  // rebuildTaskMeta — reconstructs the `:metadata` portion from components.
  // Omits __auto_ IDs (they are generated by the parser for tasks that had no id).
  function rebuildTaskMeta(status, id, startDate, endDate, after) {
    var parts = [];
    if (status) parts.push(status);
    if (id && !window.MA.parserUtils.isAutoId(id)) parts.push(id);
    if (after && !startDate) {
      parts.push('after ' + after);
    } else if (startDate) {
      parts.push(startDate);
    }
    if (endDate) parts.push(endDate);
    return parts.join(', ');
  }

  // parseGantt — pure function: text → ParsedData
  // ParsedData = {
  //   title: string,
  //   dateFormat: string,
  //   axisFormat: string,
  //   sections: [{ name: string, line: number }],
  //   tasks: [{
  //     id: string, label: string, status: string|null,
  //     startDate: string|null, endDate: string|null,
  //     after: string|null, line: number, sectionIndex: number
  //   }]
  // }
  function parseGantt(text) {
    var result = {
      title: '',
      dateFormat: 'YYYY-MM-DD',
      axisFormat: '',
      sections: [],
      tasks: [],
    };

    if (!text || !text.trim()) {
      return result;
    }

    var lines = text.split('\n');
    var autoIdCounter = 0;
    var currentSectionIndex = -1;

    for (var i = 0; i < lines.length; i++) {
      var lineNum = i + 1;  // 1-based
      var raw = lines[i];
      var trimmed = raw.trim();

      // Skip empty lines, 'gantt' keyword, and comments
      if (!trimmed || trimmed === 'gantt' || trimmed.indexOf('%%') === 0) {
        continue;
      }

      // Directives we acknowledge but don't store
      if (trimmed.indexOf('excludes') === 0 || trimmed.indexOf('todayMarker') === 0) {
        continue;
      }

      // title
      if (trimmed.indexOf('title ') === 0) {
        result.title = trimmed.slice('title '.length).trim();
        continue;
      }

      // dateFormat
      if (trimmed.indexOf('dateFormat ') === 0) {
        result.dateFormat = trimmed.slice('dateFormat '.length).trim();
        continue;
      }

      // axisFormat
      if (trimmed.indexOf('axisFormat ') === 0) {
        result.axisFormat = trimmed.slice('axisFormat '.length).trim();
        continue;
      }

      // section
      if (trimmed.indexOf('section ') === 0) {
        var sectionName = trimmed.slice('section '.length).trim();
        result.sections.push({ name: sectionName, line: lineNum });
        currentSectionIndex = result.sections.length - 1;
        continue;
      }

      // Task line — must contain ':'
      if (trimmed.indexOf(':') === -1) {
        continue;
      }

      var p = parseTaskLine(raw);
      if (!p) continue;

      // Auto-generate id if not set
      var taskId = p.id !== null ? p.id : window.MA.parserUtils.generateAutoId('auto', autoIdCounter++);

      result.tasks.push({
        id: taskId,
        label: p.label,
        status: p.status,
        startDate: p.startDate,
        endDate: p.endDate,
        after: p.after,
        line: lineNum,
        sectionIndex: currentSectionIndex,
      });
    }

    return result;
  }

  // updateTaskDates — replaces dates on the line at 1-based lineNum.
  // Pass null for newStart or newEnd to leave that value unchanged.
  // When newStart is provided, any 'after' dependency is cleared.
  function updateTaskDates(text, lineNum, newStart, newEnd) {
    var lines = text.split('\n');
    var idx = lineNum - 1;
    if (idx < 0 || idx >= lines.length) return text;

    var parsed = parseTaskLine(lines[idx]);
    if (!parsed) return text;

    var start = newStart !== null && newStart !== undefined ? newStart : parsed.startDate;
    var end   = newEnd   !== null && newEnd   !== undefined ? newEnd   : parsed.endDate;
    // If a new start is given, clear 'after' dependency
    var after = (newStart !== null && newStart !== undefined) ? null : parsed.after;

    var meta = rebuildTaskMeta(parsed.status, parsed.id, start, end, after);
    lines[idx] = parsed.indent + parsed.label + ' :' + meta;
    return lines.join('\n');
  }

  // updateTaskField — updates label, status, or id on the line at 1-based lineNum.
  // Pass null to remove status.
  function updateTaskField(text, lineNum, field, value) {
    var lines = text.split('\n');
    var idx = lineNum - 1;
    if (idx < 0 || idx >= lines.length) return text;

    var parsed = parseTaskLine(lines[idx]);
    if (!parsed) return text;
    var oldId = parsed.id;

    if (field === 'label') {
      parsed.label = value;
    } else if (field === 'status') {
      var wasMilestone = parsed.status === 'milestone';
      parsed.status = value || null;
      // status is the single source of truth for "is this a milestone", so the
      // line shape has to follow it. `0d` is not decoration: without it mermaid
      // cannot resolve the milestone's extent and drops it (F7), so marking a
      // task as a milestone would make it vanish. Leaving `0d` behind on the way
      // out is the same failure mirrored — a zero-width bar.
      if (parsed.status === 'milestone') {
        parsed.endDate = '0d';
      } else if (wasMilestone && parsed.endDate === '0d') {
        // Not null: `納品 :m1, 2026-04-01` with no third field makes mermaid read
        // the id as a date and refuse the whole chart ("Invalid date:m1"). The
        // unit test that only asserted "0d is gone" passed on that output — the
        // render oracle is what caught it. 1d is the shortest task that is still
        // a task; 0d would be the milestone we are leaving.
        parsed.endDate = '1d';
      }
    } else if (field === 'id') {
      parsed.id = value;
    } else if (field === 'after') {
      if (value && value.trim()) {
        parsed.after = value.trim();
        parsed.startDate = null; // after指定時はstartDateをクリア
      } else {
        parsed.after = null;
      }
    }

    var meta = rebuildTaskMeta(parsed.status, parsed.id, parsed.startDate, parsed.endDate, parsed.after);
    lines[idx] = parsed.indent + parsed.label + ' :' + meta;
    if (field === 'id' && value !== oldId) renameAfterRefs(lines, oldId, value, idx);
    return lines.join('\n');
  }

  // Rewrite `after <id>` dependencies when a task id is renamed. Leaving them
  // dangling is the quietest failure of the three the GUI can produce: mermaid
  // parses and renders the chart without complaint, but resolves the unknown
  // reference somewhere else entirely — a bar measured at x=132 moved to x=1128
  // (March to June on the same chart) with no error and no visual cue that the
  // dependency was lost.
  //
  // Only the token right after `after`/`until` is an id; task labels are free
  // text and keep the old string even when it matches.
  function renameAfterRefs(lines, oldId, newId, skipIdx) {
    for (var j = 0; j < lines.length; j++) {
      if (j === skipIdx) continue;
      var p = parseTaskLine(lines[j]);
      if (!p || !p.after) continue;
      // `after a b` chains several dependencies on one task.
      var deps = p.after.split(/\s+/).map(function(d) { return d === oldId ? newId : d; });
      var joined = deps.join(' ');
      if (joined === p.after) continue;
      lines[j] = p.indent + p.label + ' :' +
        rebuildTaskMeta(p.status, p.id, p.startDate, p.endDate, joined);
    }
  }

  // addTask — inserts a new task line at the end of the section identified by
  // sectionIndex (0-based, from parseGantt result). Pass -1 to append at end of
  // the whole diagram.
  // Next unused auto id.
  //
  // The old `'t' + (++addCounter)` counter lived in app.js and knew nothing about
  // the document: reopening a file, or deleting and re-adding, produced an id
  // that already existed. Two tasks with the same id make `after <id>` point at
  // whichever one mermaid saw last, so a dependency silently moves.
  function nextTaskId(text) {
    var used = {};
    var tasks = parseGantt(text).tasks;
    for (var i = 0; i < tasks.length; i++) {
      if (tasks[i].id) used[tasks[i].id] = true;
    }
    var n = 1;
    while (used['t' + n]) n++;
    return 't' + n;
  }

  // The task the next one should follow on from: the last task of the section
  // whose start and end are *both* plain dates.
  //
  // Anything else (a duration, an `after` reference, a missing value) returns
  // null and the caller leaves the date fields empty. Guessing a resolved date
  // and filling it in silently is worse: F9 showed the naive version producing
  // either an exception or a 1970-01-01, and a wrong date that looks right is
  // harder to notice than a blank field.
  function lastResolvedTask(text, sectionIndex) {
    if (!text) return null;
    var parsed = parseGantt(text);
    var sections = parsed.sections || [];
    var tasks = parsed.tasks || [];
    var inSection = tasks.filter(function(t) {
      if (sectionIndex === -1 || sections.length === 0) return true;
      return t.sectionIndex === sectionIndex;
    });
    if (inSection.length === 0) return null;
    var last = inSection[inSection.length - 1];
    if (!last.startDate || !last.endDate) return null;
    if (!DATE_RE.test(last.startDate) || !DATE_RE.test(last.endDate)) return null;
    return last;
  }

  function nextStartDate(text, sectionIndex) {
    var last = lastResolvedTask(text, sectionIndex);
    return last ? last.endDate : null;
  }

  function nextDurationDays(text, sectionIndex) {
    var last = lastResolvedTask(text, sectionIndex);
    if (!last) return null;
    var days = window.MA.dateUtils.daysBetween(last.startDate, last.endDate);
    return (typeof days === 'number' && isFinite(days)) ? days : null;
  }

  // `0d` is not optional: without it mermaid cannot resolve the milestone's
  // extent and drops it from the chart (F7).
  function milestoneMeta(id, date) {
    return rebuildTaskMeta('milestone', id, date, '0d', null);
  }

  function addTask(text, sectionIndex, label, id, startDate, endDate, status) {
    var lines = text.split('\n');
    var parsed = parseGantt(text);
    var newLine = '    ' + label + ' :' + rebuildTaskMeta(status || null, id, startDate, endDate, null);

    var insertAt; // index in lines array AFTER which we insert (we splice at insertAt+1)

    if (sectionIndex === -1 || parsed.sections.length === 0) {
      // Append at end of file (trim trailing empty lines to keep it tidy)
      insertAt = lines.length - 1;
      // Back up past trailing empty lines
      while (insertAt > 0 && lines[insertAt].trim() === '') insertAt--;
      lines.splice(insertAt + 1, 0, newLine);
      return lines.join('\n');
    }

    // Find the last task line that belongs to this section, or fall back to the
    // section header line itself.
    var sectionLine = parsed.sections[sectionIndex].line; // 1-based
    var lastLineInSection = sectionLine; // 1-based, will advance

    // The next section starts at…
    var nextSectionLine = parsed.sections.length > sectionIndex + 1
      ? parsed.sections[sectionIndex + 1].line  // 1-based
      : lines.length + 1;                        // sentinel beyond end

    // Walk tasks to find the last one in this section
    for (var i = 0; i < parsed.tasks.length; i++) {
      if (parsed.tasks[i].sectionIndex === sectionIndex) {
        if (parsed.tasks[i].line > lastLineInSection) {
          lastLineInSection = parsed.tasks[i].line;
        }
      }
    }

    // Make sure we don't overshoot into the next section
    if (lastLineInSection >= nextSectionLine) {
      lastLineInSection = nextSectionLine - 1;
    }

    // Insert after lastLineInSection (convert to 0-based index)
    lines.splice(lastLineInSection, 0, newLine); // splice(lastLineInSection, 0, ...) inserts AFTER that index (0-based = 1-based - 1 + 1)
    return lines.join('\n');
  }

  // deleteTask — removes the line at 1-based lineNum.
  function deleteTask(text, lineNum) {
    return window.MA.textUpdater.deleteLine(text, lineNum);
  }

  // sanitizeAfterDependencies — adjusts dependent task end dates to maintain validity.
  function sanitizeAfterDependencies(text) {
    var p = parseGantt(text);
    var lines = text.split('\n');
    var changed = false;

    for (var i = 0; i < p.tasks.length; i++) {
      var t = p.tasks[i];
      if (!t.after) continue;

      // Find the referenced task
      var ref = null;
      for (var j = 0; j < p.tasks.length; j++) {
        if (p.tasks[j].id === t.after) { ref = p.tasks[j]; break; }
      }
      if (!ref) continue;

      // Resolve the referenced task's end date
      var refEnd = ref.endDate;
      if (!refEnd || !DATE_RE.test(refEnd)) continue;

      // Check if this task's end date is before the ref's end date
      if (t.endDate && DATE_RE.test(t.endDate)) {
        if (window.MA.dateUtils.daysBetween(refEnd, t.endDate) < 1) {
          // Push end date to refEnd + 1 day
          var newEnd = window.MA.dateUtils.addDays(refEnd, 1);
          var parsed = parseTaskLine(lines[t.line - 1]);
          if (parsed) {
            var meta = rebuildTaskMeta(parsed.status, parsed.id, parsed.startDate, newEnd, parsed.after);
            lines[t.line - 1] = parsed.indent + parsed.label + ' :' + meta;
            changed = true;
          }
        }
      }
    }

    return changed ? lines.join('\n') : text;
  }

  // addSection — appends a new section at the end of the diagram.
  function addSection(text, name) {
    var lines = text.split('\n');
    // Append at end (before trailing empty lines)
    var insertIdx = lines.length;
    while (insertIdx > 0 && lines[insertIdx - 1].trim() === '') insertIdx--;
    lines.splice(insertIdx, 0, '', '    section ' + name);
    return lines.join('\n');
  }

  // Days a duration token covers. mermaid accepts d/w/M/y (and h/s, which round to
  // nothing useful here); anything else is not a duration.
  function durationDays(token) {
    if (!isDuration(token)) return null;
    var n = parseInt(token, 10);
    var unit = token.slice(String(n).length);
    if (unit === 'd') return n;
    if (unit === 'w') return n * 7;
    if (unit === 'M') return Math.round(n * 30.44);
    if (unit === 'y') return Math.round(n * 365.25);
    return 0; // h / s / m — sub-day, contributes nothing to a day-grained span
  }

  // The real date range a chart covers, with `after` references and durations
  // resolved the way mermaid resolves them. Reading startDate/endDate directly
  // does not work: they hold raw tokens, so a chart written as
  // `A :a1, 2026-01-01, 365d` / `B :a2, after a1, 365d` — the most ordinary way to
  // write a gantt — exposes exactly one ISO date and looks like a single day.
  // Returns null when no task has a resolvable anchor date.
  function resolveSpan(parsedData) {
    if (!parsedData || !parsedData.tasks || !parsedData.tasks.length) return null;
    var addDays = window.MA.dateUtils.addDays;
    var ends = {};   // task id -> resolved end date
    var prevEnd = null;
    var min = null, max = null;

    for (var i = 0; i < parsedData.tasks.length; i++) {
      var t = parsedData.tasks[i];
      var start = null;

      if (t.startDate && isDate(t.startDate)) {
        start = t.startDate;
      } else if (t.after && ends[t.after]) {
        start = ends[t.after];
      } else if (prevEnd) {
        // No anchor of its own (bare duration, or an `after` we could not resolve):
        // mermaid continues from the previous task.
        start = prevEnd;
      }
      if (!start) continue; // nothing anchors this task yet

      // `A :a1, 5d` puts the duration in startDate, not endDate — the parser fills
      // positionally and there is no start to fill. Take whichever slot holds it.
      var lengthToken = (t.endDate && !isDate(t.endDate)) ? t.endDate
        : (t.startDate && !isDate(t.startDate)) ? t.startDate
        : null;

      var end = start;
      if (t.endDate && isDate(t.endDate)) {
        end = t.endDate;
      } else if (lengthToken) {
        var d = durationDays(lengthToken);
        if (d !== null) end = addDays(start, d);
      }

      ends[t.id] = end;
      prevEnd = end;
      if (!min || start < min) min = start;
      if (!max || end > max) max = end;
    }

    if (!min || !max) return null;
    var days = window.MA.dateUtils.daysBetween(min, max);
    if (!isFinite(days) || days < 0) return null;
    return { min: min, max: max, days: Math.max(1, days) };
  }

  // The lines a section owns: its own `section` line through the line before the
  // next section, blank lines at the end trimmed off. deleteSection also swallows
  // the blank line *before* the header; moveSection deliberately does not, because
  // carrying it along would drift the separators every time a section is moved.
  function sectionBlock(lines, sections, secIdx) {
    var start = sections[secIdx].line - 1;
    var end = (secIdx + 1 < sections.length) ? sections[secIdx + 1].line - 1 : lines.length;
    while (end > start + 1 && lines[end - 1].trim() === '') end--;
    return { start: start, end: end };
  }

  // moveSection — swaps a section, with the tasks it contains, past its neighbour.
  // direction: -1 = earlier, +1 = later. A move at either edge is a no-op.
  function moveSection(text, sectionLine, direction) {
    if (direction !== -1 && direction !== 1) return text;
    var lines = text.split('\n');
    var sections = parseGantt(text).sections;
    var idx = -1;
    for (var i = 0; i < sections.length; i++) {
      if (sections[i].line === sectionLine) { idx = i; break; }
    }
    if (idx === -1) return text;
    var other = idx + direction;
    if (other < 0 || other >= sections.length) return text;

    var a = sectionBlock(lines, sections, Math.min(idx, other));
    var b = sectionBlock(lines, sections, Math.max(idx, other));
    var blockA = lines.slice(a.start, a.end);
    var blockB = lines.slice(b.start, b.end);
    // Whatever sat between the two blocks (usually one blank line) stays between
    // them, so the separator does not travel with the section.
    var between = lines.slice(a.end, b.start);

    var out = lines.slice(0, a.start)
      .concat(blockB, between, blockA, lines.slice(b.end));
    return out.join('\n');
  }

  // deleteSection — removes the section and all its tasks.
  function deleteSection(text, sectionLine) {
    var lines = text.split('\n');
    var p = parseGantt(text);
    var secIdx = -1;
    for (var i = 0; i < p.sections.length; i++) {
      if (p.sections[i].line === sectionLine) { secIdx = i; break; }
    }
    if (secIdx === -1) return text;
    // Find range: from section line to next section (or end)
    var startIdx = sectionLine - 1;
    var endIdx;
    if (secIdx + 1 < p.sections.length) {
      endIdx = p.sections[secIdx + 1].line - 1;
    } else {
      endIdx = lines.length;
    }
    // Remove blank line before section if present
    if (startIdx > 0 && lines[startIdx - 1].trim() === '') startIdx--;
    lines.splice(startIdx, endIdx - startIdx);
    return lines.join('\n');
  }

  // updateGlobalSetting — updates or inserts a global directive (title, dateFormat, axisFormat).
  function updateGlobalSetting(text, key, value) {
    var lines = text.split('\n');
    var found = false;
    for (var i = 0; i < lines.length; i++) {
      if (lines[i].trim().indexOf(key + ' ') === 0) {
        lines[i] = '    ' + key + ' ' + value;
        found = true;
        break;
      }
    }
    if (!found) {
      // Insert after 'gantt' line
      for (var j = 0; j < lines.length; j++) {
        if (lines[j].trim() === 'gantt') {
          lines.splice(j + 1, 0, '    ' + key + ' ' + value);
          break;
        }
      }
    }
    return lines.join('\n');
  }

  // Drop a global directive line entirely.
  //
  // Needed because "no axisFormat line" is a meaningful state, not just an
  // absence: the app then picks the tick granularity from the project span. The
  // properties panel offers it as「自動」, so it has to be able to get back there
  // once the user has chosen a fixed format.
  //
  // The key is matched at the start of the trimmed line and must be followed by
  // whitespace, so removing `Format` cannot take `dateFormat` with it.
  function removeGlobalSetting(text, key) {
    var lines = text.split('\n');
    var out = [];
    for (var i = 0; i < lines.length; i++) {
      var t = lines[i].trim();
      if (t.indexOf(key) === 0 && /\s/.test(t.charAt(key.length))) continue;
      out.push(lines[i]);
    }
    return out.join('\n');
  }

  // moveTaskWithinSection — moves the task at 1-based lineNum up (-1) or down (+1)
  // within its current section.
  function moveTaskWithinSection(text, lineNum, direction) {
    if (direction !== -1 && direction !== 1) return text;
    var p = parseGantt(text);
    var task = null;
    for (var i = 0; i < p.tasks.length; i++) {
      if (p.tasks[i].line === lineNum) { task = p.tasks[i]; break; }
    }
    if (!task) return text;

    // Tasks in the same section, sorted by line
    var siblings = p.tasks.filter(function(t) { return t.sectionIndex === task.sectionIndex; });
    siblings.sort(function(a, b) { return a.line - b.line; });
    var idx = -1;
    for (var si = 0; si < siblings.length; si++) {
      if (siblings[si].line === lineNum) { idx = si; break; }
    }
    if (idx === -1) return text;

    var swapIdx = idx + direction;
    if (swapIdx < 0 || swapIdx >= siblings.length) return text; // boundary

    return window.MA.textUpdater.swapLines(text, lineNum, siblings[swapIdx].line);
  }

  // moveTaskToSection — moves the task at 1-based lineNum to the end of the
  // section identified by targetSectionIndex (0-based).
  function moveTaskToSection(text, lineNum, targetSectionIndex) {
    var p = parseGantt(text);
    var task = null;
    for (var i = 0; i < p.tasks.length; i++) {
      if (p.tasks[i].line === lineNum) { task = p.tasks[i]; break; }
    }
    if (!task) return text;
    if (task.sectionIndex === targetSectionIndex) return text; // already there
    if (targetSectionIndex < -1 || targetSectionIndex >= p.sections.length) return text;

    // Capture the original task line content
    var lines = text.split('\n');
    var taskLineContent = lines[lineNum - 1];

    // Delete the original line first
    var afterDelete = deleteTask(text, lineNum);

    // Re-parse the post-delete state and find the insertion point at the target section
    var p2 = parseGantt(afterDelete);
    var lines2 = afterDelete.split('\n');
    var insertAt;

    if (targetSectionIndex === -1 || p2.sections.length === 0) {
      // Append at end (trim trailing empty lines)
      insertAt = lines2.length;
      while (insertAt > 0 && lines2[insertAt - 1].trim() === '') insertAt--;
    } else {
      var sectionLine = p2.sections[targetSectionIndex].line; // 1-based
      var nextSectionLine = (targetSectionIndex + 1 < p2.sections.length)
        ? p2.sections[targetSectionIndex + 1].line
        : lines2.length + 1;
      var lastLineInSection = sectionLine;
      for (var ti = 0; ti < p2.tasks.length; ti++) {
        if (p2.tasks[ti].sectionIndex === targetSectionIndex && p2.tasks[ti].line > lastLineInSection) {
          lastLineInSection = p2.tasks[ti].line;
        }
      }
      if (lastLineInSection >= nextSectionLine) lastLineInSection = nextSectionLine - 1;
      insertAt = lastLineInSection; // 0-based: insert at this index = after lastLineInSection (1-based)
    }

    lines2.splice(insertAt, 0, taskLineContent);
    return lines2.join('\n');
  }

  // ── Calibration (ADR-010) ─────────────────────────────────────────────────
  var calibration = { pxPerDay: 0, originX: 0, baseDate: '', barRects: [] };

  // A milestone rect, identified without relying on getBBox: mermaid marks it with
  // the `milestone` class, and hand-authored SVG may only carry the rotation. Both
  // signals mean the box we would measure is not aligned to the timeline.
  function isMilestoneRect(rect) {
    if (!rect) return false;
    var cls = rect.getAttribute && rect.getAttribute('class');
    if (cls && cls.indexOf('milestone') !== -1) return true;
    var tr = rect.getAttribute && rect.getAttribute('transform');
    if (tr && /rotate\s*\(/.test(tr)) return true;
    return false;
  }

  function calibrateScale(svgEl, parsedData) {
    calibration = { pxPerDay: 0, originX: 0, baseDate: '', barRects: [] };
    if (!svgEl || !parsedData || !parsedData.tasks || parsedData.tasks.length === 0) return;

    // ── Match tasks to SVG rects via text label y-position proximity ──
    // Step 1: Collect all text elements and their y-centers
    var textEls = svgEl.querySelectorAll('text');
    var labelInfos = []; // {text, yCenter}
    for (var ti2 = 0; ti2 < textEls.length; ti2++) {
      try {
        var tbb = textEls[ti2].getBBox();
        labelInfos.push({ text: textEls[ti2].textContent.trim(), yCenter: tbb.y + tbb.height / 2 });
      } catch (e) { /* skip */ }
    }

    // Step 2: Collect candidate bar rects (reasonable size, not full-width backgrounds)
    var vb = svgEl.viewBox.baseVal;
    var chartWidth = vb ? vb.width : 2000;
    var allRects = svgEl.querySelectorAll('rect');
    // mermaid labels its bars `class="task ..."` and its row backgrounds
    // `class="section ..."`, so ask it directly instead of guessing from size.
    //
    // The old test was "narrower than 95% of the chart". A section background
    // sits at exactly the same yCenter as the bar on its row, so once it becomes
    // a candidate the two tie on distance and DOM order decides — and the
    // background comes first. In detail mode the background happened to be wider
    // than the threshold and got dropped; in overview mode, where the chart is
    // redrawn at the container width, it is not. Measured at 718px wide: the
    // background is 680.5px against a 682.1px threshold, so the first task's
    // grab area became x=0 w=680.5 instead of x=75 w=181 and dragging moved
    // nothing at all.
    var classed = [];
    for (var cli = 0; cli < allRects.length; cli++) {
      var cls = allRects[cli].getAttribute && allRects[cli].getAttribute('class');
      if (cls && /(^|\s)task(\s|$)/.test(cls)) classed.push(allRects[cli]);
    }
    // Fall back to the geometric guess only when nothing carries the class at
    // all — a mermaid upgrade that renames it should degrade to the old
    // behaviour rather than silently disabling drag everywhere.
    var pool = classed.length > 0 ? classed : allRects;
    var byClass = classed.length > 0;
    var candidateRects = []; // {x, y, width, height, yCenter}
    for (var cri = 0; cri < pool.length; cri++) {
      try {
        // Milestones are drawn as a 20x20 rect rotated 45deg. getBBox() reports the
        // un-rotated box, so its x is the corner of a square that has nothing to do
        // with the milestone's date — feeding it to the fit makes pxPerDay wrong for
        // every other task. Measured: one milestone moved pxPerDay 19.267 -> 18.571
        // and shifted an unrelated task's computed date by a day.
        if (isMilestoneRect(pool[cri])) continue;
        var rbb = pool[cri].getBBox();
        if (byClass) {
          candidateRects.push({ x: rbb.x, y: rbb.y, width: rbb.width, height: rbb.height, yCenter: rbb.y + rbb.height / 2, used: false });
          continue;
        }
        // Task bars: reasonable height (8-40px), not too wide (< 95% of chart), minimum width
        if (rbb.height >= 8 && rbb.height <= 40 && rbb.width >= 1 && rbb.width < chartWidth * 0.95) {
          candidateRects.push({ x: rbb.x, y: rbb.y, width: rbb.width, height: rbb.height, yCenter: rbb.y + rbb.height / 2, used: false });
        }
      } catch (e) { /* skip */ }
    }

    // How far a rect may sit from its label before it belongs to a different row.
    // A fixed 30px threshold exceeded the 24px row pitch, so whenever a task's own
    // bar was missing the search happily took the next row's — and dragging that
    // bar rewrote a different task's dates. Derive the tolerance from the observed
    // pitch instead, and never let it reach a full row.
    var rowTolerance = 12;
    var ys = labelInfos.map(function(l) { return l.yCenter; }).sort(function(a, b) { return a - b; });
    var gaps = [];
    for (var gi = 1; gi < ys.length; gi++) {
      var gap = ys[gi] - ys[gi - 1];
      if (gap > 0.5) gaps.push(gap);
    }
    if (gaps.length) {
      gaps.sort(function(a, b) { return a - b; });
      var pitch = gaps[Math.floor(gaps.length / 2)]; // median, so one odd row cannot skew it
      rowTolerance = Math.max(4, pitch * 0.45);
    }

    // Step 3: For each task, find its text label, then find the closest candidate rect
    var barRects = []; // one per task (or null)
    for (var ti = 0; ti < parsedData.tasks.length; ti++) {
      var task = parsedData.tasks[ti];
      var taskLabel = task.label.trim();

      // Find matching text label
      var labelY = null;
      for (var li = 0; li < labelInfos.length; li++) {
        if (labelInfos[li].text === taskLabel) {
          labelY = labelInfos[li].yCenter;
          labelInfos.splice(li, 1); // consume it so duplicate labels map to different rects
          break;
        }
      }

      if (labelY === null) {
        barRects.push(null);
        continue;
      }

      // Find closest unused candidate rect by y-center
      var closest = null;
      var closestDist = Infinity;
      for (var ri = 0; ri < candidateRects.length; ri++) {
        if (candidateRects[ri].used) continue;
        var dist = Math.abs(candidateRects[ri].yCenter - labelY);
        if (dist < closestDist) {
          closestDist = dist;
          closest = ri;
        }
      }

      if (closest !== null && closestDist <= rowTolerance) {
        candidateRects[closest].used = true;
        var cr = candidateRects[closest];
        barRects.push({ x: cr.x, y: cr.y, width: cr.width, height: cr.height });
      } else {
        barRects.push(null);
      }
    }
    calibration.barRects = barRects;

    // ── Calibrate pxPerDay from tasks with known dates ──
    var calibrated = false;
    var tasksWithDates = [];
    for (var di = 0; di < parsedData.tasks.length; di++) {
      if (parsedData.tasks[di].startDate && DATE_RE.test(parsedData.tasks[di].startDate) && barRects[di]) {
        tasksWithDates.push({ task: parsedData.tasks[di], rect: barRects[di] });
      }
    }

    // Two-task calibration
    for (var ci = 0; ci < tasksWithDates.length && !calibrated; ci++) {
      for (var cj = ci + 1; cj < tasksWithDates.length && !calibrated; cj++) {
        var t1 = tasksWithDates[ci], t2 = tasksWithDates[cj];
        if (t1.task.startDate === t2.task.startDate) continue;
        var dDays = window.MA.dateUtils.daysBetween(t1.task.startDate, t2.task.startDate);
        if (dDays === 0) continue;
        calibration.pxPerDay = (t2.rect.x - t1.rect.x) / dDays;
        calibration.originX = t1.rect.x;
        calibration.baseDate = t1.task.startDate;
        calibrated = true;
      }
    }

    // Single-task fallback.
    //
    // The end used to have to be a `YYYY-MM-DD`, which excluded the most common
    // way of writing a gantt:
    //
    //     設計 :t1, 2026-03-01, 10d
    //     実装 :t2, after t1, 10d
    //
    // Neither task qualifies — the second has no start date at all — so pxPerDay
    // stayed 0 and dragging did nothing. The bars and the resize handles were
    // still drawn, so the diagram looked interactive and simply was not.
    //
    // A duration is a number of days too; there is no reason to refuse it.
    if (!calibrated && tasksWithDates.length >= 1) {
      for (var si = 0; si < tasksWithDates.length && !calibrated; si++) {
        var st = tasksWithDates[si];
        var dur = null;
        if (st.task.endDate && DATE_RE.test(st.task.endDate)) {
          dur = window.MA.dateUtils.daysBetween(st.task.startDate, st.task.endDate);
        } else if (st.task.endDate) {
          dur = durationDays(st.task.endDate);
        }
        // 0d (a milestone) would divide by zero, and an unparseable token would
        // invent a scale out of nothing. Both are better left uncalibrated.
        if (typeof dur === 'number' && isFinite(dur) && dur > 0 && st.rect.width > 0) {
          calibration.pxPerDay = st.rect.width / dur;
          calibration.originX = st.rect.x;
          calibration.baseDate = st.task.startDate;
          calibrated = true;
        }
      }
    }
  }

  function pxToDate(px) {
    if (calibration.pxPerDay === 0) return null;
    var daysDelta = Math.round((px - calibration.originX) / calibration.pxPerDay);
    return window.MA.dateUtils.addDays(calibration.baseDate, daysDelta);
  }

  function dateToPx(dateStr) {
    if (calibration.pxPerDay === 0) return 0;
    return calibration.originX + window.MA.dateUtils.daysBetween(calibration.baseDate, dateStr) * calibration.pxPerDay;
  }

  // ── Module export ──
  // gantt のオーバーレイ。他の20図種と同じ 3引数契約 (ADR-012) に揃えた。
  //
  // 以前は app.js のクロージャ変数 overlayEl を直接見ていたため、app.js から出せなかった。
  // 実測したら外部依存は overlayEl の1つだけだったので、引数で受ければ移せる。
  function buildOverlay(svgEl, parsedData, overlayEl) {
    if (!overlayEl) return;
    // Clear previous overlay content
    while (overlayEl.firstChild) overlayEl.removeChild(overlayEl.firstChild);

    if (!svgEl || !parsedData || !parsedData.tasks || parsedData.tasks.length === 0) return;

    // Calibrate scale
    calibrateScale(svgEl, parsedData);

    // Match overlay SVG dimensions/viewBox to the mermaid SVG
    var viewBox = svgEl.getAttribute('viewBox');
    if (viewBox) {
      overlayEl.setAttribute('viewBox', viewBox);
    }
    var svgW = svgEl.getAttribute('width');
    var svgH = svgEl.getAttribute('height');
    if (svgW) overlayEl.setAttribute('width', svgW);
    if (svgH) overlayEl.setAttribute('height', svgH);

    var NS = 'http://www.w3.org/2000/svg';
    var barRects = window.MA.modules.gantt.getCalibration().barRects;

    for (var i = 0; i < parsedData.tasks.length; i++) {
      var task = parsedData.tasks[i];
      var br = i < barRects.length ? barRects[i] : null;
      if (!br) continue; // skip tasks we couldn't match to SVG rects
      var selected = window.MA.selection.isSelected(task.id);

      // If selected: add green dashed highlight rect
      if (selected) {
        var hlRect = document.createElementNS(NS, 'rect');
        hlRect.setAttribute('x', br.x - 2);
        hlRect.setAttribute('y', br.y - 2);
        hlRect.setAttribute('width', br.width + 4);
        hlRect.setAttribute('height', br.height + 4);
        hlRect.setAttribute('fill', 'none');
        hlRect.setAttribute('stroke', '#7ee787');
        hlRect.setAttribute('stroke-width', '2');
        hlRect.setAttribute('stroke-dasharray', '4');
        hlRect.setAttribute('rx', '3');
        overlayEl.appendChild(hlRect);
      }

      // Transparent overlay bar rect
      var overlayRect = document.createElementNS(NS, 'rect');
      overlayRect.setAttribute('x', br.x);
      overlayRect.setAttribute('y', br.y);
      overlayRect.setAttribute('width', br.width);
      overlayRect.setAttribute('height', br.height);
      overlayRect.setAttribute('fill', 'transparent');
      overlayRect.setAttribute('cursor', 'move');
      overlayRect.setAttribute('class', 'overlay-bar');
      overlayRect.setAttribute('data-task-id', task.id);
      overlayRect.setAttribute('data-type', 'task');
      overlayRect.setAttribute('data-line', task.line);
      overlayRect.setAttribute('data-index', i);
      overlayEl.appendChild(overlayRect);

      // Left resize handle
      var leftHandle = document.createElementNS(NS, 'rect');
      leftHandle.setAttribute('x', br.x);
      leftHandle.setAttribute('y', br.y);
      leftHandle.setAttribute('width', '6');
      leftHandle.setAttribute('height', br.height);
      leftHandle.setAttribute('fill', selected ? '#7ee787' : 'transparent');
      leftHandle.setAttribute('opacity', selected ? '0.7' : '0');
      leftHandle.setAttribute('cursor', 'w-resize');
      leftHandle.setAttribute('class', 'resize-handle');
      leftHandle.setAttribute('data-task-id', task.id);
      leftHandle.setAttribute('data-handle', 'left');
      leftHandle.setAttribute('data-line', task.line);
      leftHandle.setAttribute('data-index', i);
      overlayEl.appendChild(leftHandle);

      // Right resize handle
      var rightHandle = document.createElementNS(NS, 'rect');
      rightHandle.setAttribute('x', br.x + br.width - 6);
      rightHandle.setAttribute('y', br.y);
      rightHandle.setAttribute('width', '6');
      rightHandle.setAttribute('height', br.height);
      rightHandle.setAttribute('fill', selected ? '#7ee787' : 'transparent');
      rightHandle.setAttribute('opacity', selected ? '0.7' : '0');
      rightHandle.setAttribute('cursor', 'e-resize');
      rightHandle.setAttribute('class', 'resize-handle');
      rightHandle.setAttribute('data-task-id', task.id);
      rightHandle.setAttribute('data-handle', 'right');
      rightHandle.setAttribute('data-line', task.line);
      rightHandle.setAttribute('data-index', i);
      overlayEl.appendChild(rightHandle);
    }
  }

  // 追加フォームの状態。gantt 固有なので app.js ではなくここで持つ。
  var addForm = { label: '', id: '', start: '', end: '', kind: 'task', focus: null };
  function setAddFormFocus(field) { addForm.focus = field; }

  // 文書が入れ替わったときの後始末。
  //
  // 追加フォームの入力は前の文書に紐づくものなので、図種を切り替えたり
  // ファイルを開いたら捨てる。残しておくと、本文はひな形に置き換わっているのに
  // 入力欄にだけ前の図の名前や日付が残り、そのまま追加を押すと意図しない
  // 要素が入る。他の図種はフォームを毎回作り直すので起きないが、
  // gantt は状態をモジュール側で保持しているため明示的に消す必要がある。
  function resetTransientState() {
    addForm.label = '';
    addForm.id = '';
    addForm.start = '';
    addForm.end = '';
    addForm.section = undefined;
    addForm.kind = 'task';
    addForm.focus = null;
  }
  function addFormSectionIndex(parsedData) {
    var count = (parsedData && parsedData.sections) ? parsedData.sections.length : 0;
    if (count === 0) return -1;
    var want = parseInt(addForm.section, 10);
    if (isNaN(want) || want < 0 || want >= count) return 0;
    return want;
  }

  // gantt のプロパティ欄。他の20図種と同じ 4引数契約 (ADR-012)。
  //
  // app.js に残っていたのは、mmdText / editorEl / suppressSync / syncLineNumbers といった
  // アプリの状態を直接触っていたから。実測すると同じ形の同期ブロックが19箇所あり、
  // すべて ctx.setMmdText に1対1で対応した。外部依存は ctx の5つに収まる。
  function renderProps(selData, parsedData, propsEl, ctx) {
    if (!propsEl) return;

    // No selection
    if (!selData || selData.length === 0) {
      var sectionOptions = '';
      if (parsedData && parsedData.sections) {
        var keepSec = addFormSectionIndex(parsedData);
        for (var si = 0; si < parsedData.sections.length; si++) {
          // The chosen section has to survive the rebuild too, otherwise every
          // keystroke drops the user back to the first section.
          var selAttr = (String(si) === String(keepSec)) ? ' selected' : '';
          sectionOptions += '<option value="' + si + '"' + selAttr + '>' + window.MA.htmlUtils.escHtml(parsedData.sections[si].name) + '</option>';
        }
      }
      if (!sectionOptions) {
        sectionOptions = '<option value="-1">（セクションなし）</option>';
      }

      var sectionListHtml = '';
      if (parsedData && parsedData.sections && parsedData.sections.length > 0) {
        sectionListHtml += '<div id="prop-section-list" style="border-top:1px solid var(--border);padding-top:10px;margin-bottom:12px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:6px;">セクション一覧</label>';
        for (var sli = 0; sli < parsedData.sections.length; sli++) {
          var sec = parsedData.sections[sli];
          var taskCount = 0;
          for (var sti = 0; sti < parsedData.tasks.length; sti++) {
            if (parsedData.tasks[sti].sectionIndex === sli) taskCount++;
          }
          sectionListHtml +=
            '<div style="display:flex;align-items:center;gap:4px;margin-bottom:4px;padding:3px 4px;background:var(--bg-tertiary);border-radius:3px;">' +
              '<div style="flex:1;font-size:11px;color:var(--text-primary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;" title="' + window.MA.htmlUtils.escHtml(sec.name) + '">' + window.MA.htmlUtils.escHtml(sec.name) + ' <span style="color:var(--text-secondary);font-size:10px;">(' + taskCount + ')</span></div>' +
              '<button class="prop-section-up" data-section-line="' + sec.line + '" title="上のセクションと入れ替え" style="background:var(--bg-primary);border:1px solid var(--border);color:var(--text-primary);width:20px;height:20px;border-radius:3px;cursor:pointer;font-size:10px;padding:0;">↑</button>' +
              '<button class="prop-section-down" data-section-line="' + sec.line + '" title="下のセクションと入れ替え" style="background:var(--bg-primary);border:1px solid var(--border);color:var(--text-primary);width:20px;height:20px;border-radius:3px;cursor:pointer;font-size:10px;padding:0;">↓</button>' +
              // 巻き添えの件数をボタン自体に出す (block と同じ手)。
              // 以前はここだけ confirm を出していて、同じ画面のタスク ✕ は無言、
              // block は件数表示と、3通りの作法が混在していた。押す前に何が起きるかを
              // ボタンの文字で示し、確認は出さない (Undo で戻せる)。
              '<button class="prop-section-delete" data-section-name="' + window.MA.htmlUtils.escHtml(sec.name) + '" data-section-line="' + sec.line + '" data-task-count="' + taskCount + '" title="セクション「' + window.MA.htmlUtils.escHtml(sec.name) + '」と含まれるタスク' + taskCount + '件を削除" style="background:var(--accent-red);color:#fff;border:none;padding:2px 6px;border-radius:3px;cursor:pointer;font-size:10px;white-space:nowrap;">✕' + (taskCount > 0 ? taskCount : '') + '</button>' +
            '</div>';

          // セクションの下にタスクを並べる。
          //
          // gantt だけプロパティ欄にタスク一覧が無く、タスクを選ぶ手段が
          // 「チャート上のバーをクリックする」しか無かった。他の20図種には一覧がある。
          // 4件なら困らないが、100件になるとバーを目で探すしかなくなり、
          // 一覧を持つ他の図種との差が実務で効いてくる (R8 スケール耐性)。
          for (var tli = 0; tli < parsedData.tasks.length; tli++) {
            var tk = parsedData.tasks[tli];
            if (tk.sectionIndex !== sli) continue;
            var tkLabel = window.MA.htmlUtils.escHtml(tk.label || tk.id || '');
            var tkId = window.MA.htmlUtils.escHtml(tk.id || '');
            sectionListHtml +=
              '<div class="ma-list-row" style="display:flex;align-items:center;gap:4px;margin:0 0 3px 14px;padding:2px 4px;background:var(--bg-primary);border-radius:3px;">' +
                '<div style="flex:1;font-size:11px;color:var(--text-primary);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;" title="' + tkLabel + '">' + tkLabel + '</div>' +
                '<button class="prop-task-select" data-element-id="' + tkId + '" data-line="' + tk.line + '" title="「' + tkLabel + '」を選択" style="background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:2px 6px;border-radius:3px;cursor:pointer;font-size:10px;">編集</button>' +
                '<button class="prop-task-delete" data-element-id="' + tkId + '" data-line="' + tk.line + '" title="「' + tkLabel + '」を削除" style="background:var(--accent-red);color:#fff;border:none;padding:2px 6px;border-radius:3px;cursor:pointer;font-size:10px;">✕</button>' +
              '</div>';
          }
        }
        sectionListHtml += '</div>';
      } else {
        sectionListHtml = '<div id="prop-section-list" style="border-top:1px solid var(--border);padding-top:10px;margin-bottom:12px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:4px;">セクション一覧</label>' +
          '<div style="font-size:11px;color:var(--text-secondary);">（セクションなし）</div>' +
        '</div>';
      }

      var G = window.MA.modules.gantt;
      var addSecIdx = parseInt(addFormSectionIndex(parsedData), 10);
      var isMilestone = addForm.kind === 'milestone';
      // Only used to prefill an empty field: a value the user typed wins.
      var autoStart = G.nextStartDate(ctx.getMmdText(), addSecIdx);
      var autoDays = G.nextDurationDays(ctx.getMmdText(), addSecIdx);
      var autoEnd = (autoStart && autoDays !== null)
        ? window.MA.dateUtils.addDays(autoStart, autoDays) : '';
      var fStart = addForm.start || autoStart || '';
      var fEnd = addForm.end || autoEnd || '';
      var inputStyle = 'width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;';
      var esc = window.MA.htmlUtils.escHtml;

      propsEl.innerHTML =
        '<div style="margin-bottom:12px;font-size:11px;color:var(--text-secondary);">タスクを選択するか、新規追加</div>' +
        // 種別トグル。status を唯一の真とし、これはその入力手段でしかない。
        '<div style="margin-bottom:8px;display:flex;gap:2px;">' +
          '<button id="prop-add-kind-task" style="flex:1;background:' + (isMilestone ? 'var(--bg-tertiary)' : 'var(--accent)') + ';color:' + (isMilestone ? 'var(--text-primary)' : '#fff') + ';border:1px solid var(--border);padding:3px 4px;border-radius:3px;cursor:pointer;font-size:10px;">タスク</button>' +
          '<button id="prop-add-kind-milestone" style="flex:1;background:' + (isMilestone ? 'var(--accent)' : 'var(--bg-tertiary)') + ';color:' + (isMilestone ? '#fff' : 'var(--text-primary)') + ';border:1px solid var(--border);padding:3px 4px;border-radius:3px;cursor:pointer;font-size:10px;">マイルストーン</button>' +
        '</div>' +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">ラベル</label>' +
          '<input id="prop-add-label" type="text" value="' + esc(addForm.label || '新規タスク') + '" style="' + inputStyle + '">' +
        '</div>' +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">ID</label>' +
          '<input id="prop-add-id" type="text" value="' + esc(addForm.id) + '" placeholder="' + esc(G.nextTaskId(ctx.getMmdText())) + '" style="' + inputStyle + '">' +
        '</div>' +
        (isMilestone
          ? '<div style="margin-bottom:8px;">' +
              '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">日付</label>' +
              '<input id="prop-add-start" type="date" value="' + esc(fStart) + '" style="' + inputStyle + '">' +
            '</div>'
          : '<div style="margin-bottom:8px;">' +
              '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">開始日</label>' +
              '<input id="prop-add-start" type="date" value="' + esc(fStart) + '" style="' + inputStyle + '">' +
            '</div>' +
            '<div style="margin-bottom:8px;">' +
              '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">終了日</label>' +
              '<input id="prop-add-end" type="date" value="' + esc(fEnd) + '" style="' + inputStyle + '">' +
            '</div>') +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">セクション</label>' +
          '<select id="prop-add-section" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' + sectionOptions + '</select>' +
        '</div>' +
        '<button id="prop-add-btn" style="width:100%;background:var(--accent);color:#fff;border:none;padding:5px 8px;border-radius:4px;cursor:pointer;font-size:12px;margin-bottom:12px;">+ タスク追加</button>' +
        '<div style="border-top:1px solid var(--border);padding-top:10px;margin-top:4px;margin-bottom:12px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">セクション追加</label>' +
          '<div style="display:flex;gap:4px;">' +
            '<input id="prop-add-sec-name" type="text" placeholder="セクション名" style="flex:1;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' +
            '<button id="prop-add-sec-btn" style="background:var(--accent);color:#fff;border:none;padding:3px 10px;border-radius:3px;cursor:pointer;font-size:12px;">+</button>' +
          '</div>' +
        '</div>' +
        sectionListHtml +
        '<div style="border-top:1px solid var(--border);padding-top:10px;margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--accent);margin-bottom:6px;font-weight:bold;">グローバル設定</label>' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">title</label>' +
          '<input id="prop-global-title" type="text" value="' + window.MA.htmlUtils.escHtml(parsedData.title || '') + '" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;margin-bottom:6px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">dateFormat</label>' +
          '<input id="prop-global-dateformat" type="text" value="' + window.MA.htmlUtils.escHtml(parsedData.dateFormat || 'YYYY-MM-DD') + '" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;margin-bottom:6px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">axisFormat</label>' +
          (function() {
            var presets = [
              { v: '%Y-%m-%d', label: '2026-04-14' },
              { v: '%Y/%m/%d', label: '2026/04/14' },
              { v: '%m/%d',    label: '04/14' },
              { v: '%m月%d日', label: '04月14日' },
              { v: '%b %d',    label: 'Apr 14' },
              { v: '%d %b',    label: '14 Apr' },
              { v: '%a',       label: 'Tue (曜日)' }
            ];
            var current = parsedData.axisFormat || '';
            // No axisFormat line means the app picks the granularity from the
            // project span (ganttAxisFor). That is a real, named state — showing
            // "カスタム…" with an empty box says the user chose something custom
            // and then failed to type it, which is the opposite of what is
            // happening.
            var auto = !current;
            var matched = false;
            var opts = '<option value="__auto__"' + (auto ? ' selected' : '') +
              '>自動 (期間に合わせる)</option>';
            for (var pi = 0; pi < presets.length; pi++) {
              var sel = (presets[pi].v === current) ? ' selected' : '';
              if (sel) matched = true;
              opts += '<option value="' + window.MA.htmlUtils.escHtml(presets[pi].v) + '"' + sel + '>' + window.MA.htmlUtils.escHtml(presets[pi].label + '  (' + presets[pi].v + ')') + '</option>';
            }
            var customSel = (matched || auto) ? '' : ' selected';
            opts += '<option value="__custom__"' + customSel + '>カスタム…</option>';
            var customDisplay = (matched || auto) ? 'none' : 'block';
            return '<select id="prop-axisformat-preset" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;margin-bottom:4px;">' + opts + '</select>' +
              '<input id="prop-axisformat-custom" type="text" value="' + window.MA.htmlUtils.escHtml(current) + '" placeholder="%m/%d" style="display:' + customDisplay + ';width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">';
          })() +
        '</div>';

      // Keep every field in addForm as it is typed, so the next rebuild restores
      // it instead of resetting to the hardcoded defaults.
      ['label', 'id', 'start', 'end'].forEach(function(field) {
        var el = document.getElementById('prop-add-' + field);
        if (!el) return;
        el.addEventListener('input', function() { addForm[field] = this.value; });
        // Enter anywhere in the form adds the task — the add button is below the
        // fold on a short panel and the round trip to it is the whole friction.
        el.addEventListener('keydown', function(e) {
          if (e.key === 'Enter') { e.preventDefault(); doAddTask(); }
        });
      });
      var secSel = document.getElementById('prop-add-section');
      if (secSel) {
        secSel.addEventListener('change', function() { addForm.section = this.value; });
      }

      window.MA.properties.bindEvent('prop-add-kind-task', 'click', function() {
        addForm.kind = 'task';
        setAddFormFocus('label');
        renderProps();
      });
      window.MA.properties.bindEvent('prop-add-kind-milestone', 'click', function() {
        addForm.kind = 'milestone';
        setAddFormFocus('label');
        renderProps();
      });

      function doAddTask() {
        var labelEl = document.getElementById('prop-add-label');
        var idEl = document.getElementById('prop-add-id');
        var startEl = document.getElementById('prop-add-start');
        var endEl = document.getElementById('prop-add-end');
        var secEl = document.getElementById('prop-add-section');
        var label = (labelEl && labelEl.value) || '新規タスク';
        var id = (idEl && idEl.value) ? idEl.value : window.MA.modules.gantt.nextTaskId(ctx.getMmdText());
        var start = startEl ? startEl.value : '';
        var secIdx = secEl ? parseInt(secEl.value, 10) : -1;
        var milestone = addForm.kind === 'milestone';
        // Without a date there is nothing to place the bar at; mermaid resolves a
        // missing start to the chart origin, which reads as a task that silently
        // jumped to the beginning of the project.
        if (!start) {
          // フォーカスを移すだけでは何が起きたのか分からない。
          // 押しても何も起きないのが一番困る (C4 は「ID と Label は必須」と言うのに
          // こちらだけ無言だった) ので、理由をその場で言う。
          if (startEl) startEl.focus();
          ctx.showTransient('開始日を入れてください — 日付が無いとバーを置く位置が決まりません', 4000);
          return;
        }
        var end = milestone ? '0d' : ((endEl && endEl.value) || start);
        window.MA.history.pushHistory();
        var _t0 = addTask(ctx.getMmdText(), secIdx, label, id, start, end, milestone ? 'milestone' : null);
        // 追加したタスクを自動選択しない。
        //
        // 選択するとプロパティパネルが詳細表示に切り替わり、**追加フォームごと
        // 消える**。「ラベル欄へフォーカスを戻して連続入力」と真正面から
        // 矛盾していて、実測でも追加直後のパネルは詳細表示になり
        // prop-add-label が存在しなかった。5本続けて足したいときに毎回
        // Escape を押して戻る必要がある。
        //
        // 追加した結果は図とエディタに出るので、確認手段は失われない。
        window.MA.selection.clearSelection();
        // Clear only what identifies this task. The section and the kind are the
        // user's current context and carry over to the next add; the dates are
        // recomputed from the task just added.
        addForm.label = '';
        addForm.id = '';
        addForm.start = '';
        addForm.end = '';
        addForm.section = secEl ? secEl.value : addForm.section;
        setAddFormFocus('label');
        ctx.setMmdText(_t0);
        ctx.onUpdate();
        // renderPropsは scheduleRefresh → refresh → renderProps で自動的に呼ばれるので、追加呼び出しは不要
      }

      window.MA.properties.bindEvent('prop-add-btn', 'click', doAddTask);

      // Restore focus after the rebuild that follows an add or a kind switch.
      if (addForm.focus) {
        var focusEl = document.getElementById('prop-add-' + addForm.focus);
        addForm.focus = null;
        if (focusEl) {
          focusEl.focus();
          if (focusEl.select) focusEl.select();
        }
      }

      // Bind add section button
      var addSecBtn = document.getElementById('prop-add-sec-btn');
      if (addSecBtn) {
        addSecBtn.addEventListener('click', function() {
          var name = document.getElementById('prop-add-sec-name').value.trim();
          if (!name) return;
          window.MA.history.pushHistory();
          ctx.setMmdText(addSection(ctx.getMmdText(), name));
          ctx.onUpdate();
        });
      }

      // Bind section move buttons. Sections own the tasks between their header and
      // the next one, so moving a section carries its tasks along — the task-level
      // ↑↓ only reorders within a section.
      ['up', 'down'].forEach(function(dir) {
        var btns = propsEl.querySelectorAll('.prop-section-' + dir);
        for (var mi = 0; mi < btns.length; mi++) {
          btns[mi].addEventListener('click', function() {
            var ln = parseInt(this.getAttribute('data-section-line'), 10);
            if (isNaN(ln)) return;
            var moved = window.MA.modules.gantt.moveSection(ctx.getMmdText(), ln, dir === 'up' ? -1 : 1);
            if (moved === ctx.getMmdText()) return; // at the edge — nothing to do
            window.MA.history.pushHistory();
            ctx.setMmdText(moved);
            ctx.onUpdate();
          });
        }
      });

      // Bind section delete buttons
      var sectionDeleteBtns = propsEl.querySelectorAll('.prop-section-delete');
      for (var sdbi = 0; sdbi < sectionDeleteBtns.length; sdbi++) {
        (function(btn) {
          btn.addEventListener('click', function() {
            var secName = btn.getAttribute('data-section-name');
            var secLine = parseInt(btn.getAttribute('data-section-line'), 10);
            var secTasks = parseInt(btn.getAttribute('data-task-count'), 10) || 0;
            window.MA.history.pushHistory();
            var _t1 = deleteSection(ctx.getMmdText(), secLine);
            ctx.setMmdText(_t1);
            window.MA.selection.setSelected([]);
            ctx.showTransient('セクション「' + secName + '」とタスク' + secTasks +
              '件を削除 — Ctrl+Z で戻せます');
            ctx.onUpdate();
          });
        })(sectionDeleteBtns[sdbi]);
      }

      // Bind task list (select / delete)
      //
      // 選択は他の図種と同じく selection に載せるだけ。バーをクリックした場合と
      // 同じ状態にしたいので、id で選ぶ (行番号は編集で動く)。
      var taskSelBtns = propsEl.querySelectorAll('.prop-task-select');
      for (var tsi = 0; tsi < taskSelBtns.length; tsi++) {
        (function(btn) {
          btn.addEventListener('click', function() {
            var id = btn.getAttribute('data-element-id');
            if (!id) return;
            window.MA.selection.setSelected([{ type: 'task', id: id }]);
            ctx.onUpdate();
          });
        })(taskSelBtns[tsi]);
      }
      var taskDelBtns = propsEl.querySelectorAll('.prop-task-delete');
      for (var tdi = 0; tdi < taskDelBtns.length; tdi++) {
        (function(btn) {
          btn.addEventListener('click', function() {
            var ln = parseInt(btn.getAttribute('data-line'), 10);
            if (isNaN(ln)) return;
            window.MA.history.pushHistory();
            var _t2 = deleteTask(ctx.getMmdText(), ln);
            ctx.setMmdText(_t2);
            window.MA.selection.setSelected([]);
            ctx.onUpdate();
          });
        })(taskDelBtns[tdi]);
      }

      // Bind global settings
      function bindGlobal(elId, key) {
        var el = document.getElementById(elId);
        if (el) {
          el.addEventListener('change', function() {
            window.MA.history.pushHistory();
            ctx.setMmdText(updateGlobalSetting(ctx.getMmdText(), key, el.value));
            ctx.onUpdate();
          });
        }
      }
      bindGlobal('prop-global-title', 'title');
      bindGlobal('prop-global-dateformat', 'dateFormat');
      // axisFormat: preset dropdown + custom input
      var afPreset = document.getElementById('prop-axisformat-preset');
      var afCustom = document.getElementById('prop-axisformat-custom');
      if (afPreset) {
        afPreset.addEventListener('change', function() {
          var v = afPreset.value;
          if (v === '__custom__') {
            if (afCustom) {
              afCustom.style.display = 'block';
              afCustom.focus();
            }
            return; // don't update text yet — wait for custom input change
          }
          if (afCustom) afCustom.style.display = 'none';
          window.MA.history.pushHistory();
          // 自動 = the axisFormat line is absent, so the app derives the tick
          // granularity from the project span. Writing a value here would pin it
          // again, because the DSL line beats the config.
          if (v === '__auto__') {
            ctx.setMmdText(window.MA.modules.gantt.removeGlobalSetting(ctx.getMmdText(), 'axisFormat'));
            ctx.onUpdate();
            return;
          }
          ctx.setMmdText(updateGlobalSetting(ctx.getMmdText(), 'axisFormat', v));
          ctx.onUpdate();
        });
      }
      if (afCustom) {
        afCustom.addEventListener('change', function() {
          window.MA.history.pushHistory();
          ctx.setMmdText(updateGlobalSetting(ctx.getMmdText(), 'axisFormat', afCustom.value));
          ctx.onUpdate();
        });
      }
      return;
    }

    // Single task selected
    if (selData.length === 1 && selData[0].type === 'task') {
      var taskId = selData[0].id;
      var task = null;
      if (parsedData && parsedData.tasks) {
        for (var ti = 0; ti < parsedData.tasks.length; ti++) {
          if (parsedData.tasks[ti].id === taskId) { task = parsedData.tasks[ti]; break; }
        }
      }
      if (!task) {
        propsEl.innerHTML = '<p style="color:var(--text-secondary);font-size:11px;">タスクが見つかりません</p>';
        return;
      }

      var statusBtns = ['none', 'done', 'active', 'crit', 'milestone'].map(function(s) {
        var isActive = (s === 'none' && !task.status) || (task.status === s);
        var bg = isActive ? 'var(--accent)' : 'var(--bg-tertiary)';
        var val = s === 'none' ? '' : s;
        return '<button class="prop-status-btn" data-status="' + val + '" style="flex:1;background:' + bg + ';color:var(--text-primary);border:1px solid var(--border);padding:3px 4px;border-radius:3px;cursor:pointer;font-size:10px;">' + s + '</button>';
      }).join('');

      var moveSecOpts = '';
      if (parsedData && parsedData.sections) {
        for (var msi = 0; msi < parsedData.sections.length; msi++) {
          var selAttr = (msi === task.sectionIndex) ? ' selected' : '';
          moveSecOpts += '<option value="' + msi + '"' + selAttr + '>' + window.MA.htmlUtils.escHtml(parsedData.sections[msi].name) + '</option>';
        }
      }
      if (!moveSecOpts) {
        moveSecOpts = '<option value="-1">（セクションなし）</option>';
      }

      propsEl.innerHTML =
        '<div style="margin-bottom:12px;padding-bottom:8px;border-bottom:1px solid var(--border);display:flex;align-items:center;gap:6px;">' +
          '<div style="flex:1;font-weight:bold;color:var(--text-primary);font-size:13px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">' + window.MA.htmlUtils.escHtml(task.label) + '</div>' +
          '<button id="prop-move-up" title="同一セクション内で上へ移動" style="background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);width:24px;height:22px;border-radius:3px;cursor:pointer;font-size:12px;padding:0;">↑</button>' +
          '<button id="prop-move-down" title="同一セクション内で下へ移動" style="background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);width:24px;height:22px;border-radius:3px;cursor:pointer;font-size:12px;padding:0;">↓</button>' +
        '</div>' +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">ラベル</label>' +
          '<input id="prop-label" type="text" value="' + window.MA.htmlUtils.escHtml(task.label) + '" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' +
        '</div>' +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">ID</label>' +
          '<input id="prop-id" type="text" value="' + window.MA.htmlUtils.escHtml(window.MA.parserUtils.isAutoId(task.id) ? '' : task.id) + '" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' +
        '</div>' +
        // A milestone is a point in time; the second date field has nothing to
        // hold. status is the single source of truth for what a task is, so the
        // panel folds purely on it — the add form's kind toggle only ever writes
        // status, it never gets its own opinion.
        (task.status === 'milestone'
          ? '<div style="margin-bottom:8px;">' +
              '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">日付</label>' +
              '<input id="prop-start" type="date" value="' + window.MA.htmlUtils.escHtml(task.startDate || '') + '" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' +
            '</div>'
          : '<div style="margin-bottom:8px;">' +
              '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">開始日</label>' +
              '<input id="prop-start" type="date" value="' + window.MA.htmlUtils.escHtml(task.startDate || '') + '" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' +
            '</div>' +
            '<div style="margin-bottom:8px;">' +
              '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">終了日</label>' +
              '<input id="prop-end" type="date" value="' + window.MA.htmlUtils.escHtml(task.endDate || '') + '" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' +
            '</div>') +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">ステータス</label>' +
          '<div style="display:flex;gap:2px;">' + statusBtns + '</div>' +
        '</div>' +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">after依存</label>' +
          '<input id="prop-after" type="text" value="' + window.MA.htmlUtils.escHtml(task.after || '') + '" placeholder="タスクID (例: a1)" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' +
        '</div>' +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">セクション移動</label>' +
          '<select id="prop-move-section" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' + moveSecOpts + '</select>' +
        '</div>' +
        '<button id="prop-delete-btn" style="width:100%;background:var(--accent-red);color:#fff;border:none;padding:5px 8px;border-radius:4px;cursor:pointer;font-size:12px;margin-top:8px;">タスク削除</button>';

      // Bind handlers
      window.MA.properties.bindTextField('prop-label', task.line, 'label');
      window.MA.properties.bindTextField('prop-id', task.line, 'id');
      window.MA.properties.bindTextField('prop-after', task.line, 'after');
      window.MA.properties.bindDateField('prop-start', 'prop-end', task.line, updateTaskDates);

      // Move up/down handlers
      var moveUpBtn = document.getElementById('prop-move-up');
      if (moveUpBtn) {
        moveUpBtn.addEventListener('click', function() {
          var newText = moveTaskWithinSection(ctx.getMmdText(), task.line, -1);
          if (newText === ctx.getMmdText()) return; // no-op (boundary)
          window.MA.history.pushHistory();
          ctx.setMmdText(newText);
          ctx.onUpdate();
        });
      }
      var moveDownBtn = document.getElementById('prop-move-down');
      if (moveDownBtn) {
        moveDownBtn.addEventListener('click', function() {
          var newText = moveTaskWithinSection(ctx.getMmdText(), task.line, 1);
          if (newText === ctx.getMmdText()) return;
          window.MA.history.pushHistory();
          ctx.setMmdText(newText);
          ctx.onUpdate();
        });
      }

      var moveSectionEl = document.getElementById('prop-move-section');
      if (moveSectionEl) {
        moveSectionEl.addEventListener('change', function() {
          var targetIdx = parseInt(moveSectionEl.value, 10);
          if (isNaN(targetIdx)) return;
          var newText = moveTaskToSection(ctx.getMmdText(), task.line, targetIdx);
          if (newText === ctx.getMmdText()) return; // no-op
          window.MA.history.pushHistory();
          ctx.setMmdText(newText);
          ctx.onUpdate();
        });
      }

      // Status buttons
      var statusBtnEls = propsEl.querySelectorAll('.prop-status-btn');
      for (var sbi = 0; sbi < statusBtnEls.length; sbi++) {
        (function(btn) {
          btn.addEventListener('click', function() {
            window.MA.history.pushHistory();
            ctx.setMmdText(updateTaskField(ctx.getMmdText(), task.line, 'status', btn.getAttribute('data-status')));
            ctx.onUpdate();
          });
        })(statusBtnEls[sbi]);
      }

      // Delete button
      var delBtn = document.getElementById('prop-delete-btn');
      if (delBtn) {
        delBtn.addEventListener('click', function() {
          window.MA.history.pushHistory();
          var _t3 = deleteTask(ctx.getMmdText(), task.line);
          ctx.setMmdText(_t3);
          window.MA.selection.setSelected([]);
          ctx.onUpdate();
        });
      }
      return;
    }

    // Multiple tasks selected
    if (selData.length > 1) {
      var selectedTasks = [];
      if (parsedData && parsedData.tasks) {
        for (var mi = 0; mi < selData.length; mi++) {
          for (var mj = 0; mj < parsedData.tasks.length; mj++) {
            if (parsedData.tasks[mj].id === selData[mi].id) {
              selectedTasks.push(parsedData.tasks[mj]);
              break;
            }
          }
        }
      }

      var batchStatusBtns = ['done', 'active', 'crit', 'none'].map(function(s) {
        var val = s === 'none' ? '' : s;
        return '<button class="batch-status-btn" data-status="' + val + '" style="flex:1;background:var(--bg-tertiary);color:var(--text-primary);border:1px solid var(--border);padding:3px 4px;border-radius:3px;cursor:pointer;font-size:10px;">' + s + '</button>';
      }).join('');

      propsEl.innerHTML =
        '<div style="margin-bottom:8px;font-size:11px;color:var(--text-secondary);">' + selData.length + ' タスク選択中</div>' +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">一括ステータス変更</label>' +
          '<div style="display:flex;gap:2px;">' + batchStatusBtns + '</div>' +
        '</div>' +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">一括日付シフト（日数）</label>' +
          '<div style="display:flex;gap:4px;">' +
            '<input id="batch-shift-days" type="number" value="0" style="flex:1;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' +
            '<button id="batch-shift-btn" style="background:var(--accent);color:#fff;border:none;padding:3px 8px;border-radius:3px;cursor:pointer;font-size:11px;">適用</button>' +
          '</div>' +
        '</div>' +
        '<button id="batch-delete-btn" style="width:100%;background:var(--accent-red);color:#fff;border:none;padding:5px 8px;border-radius:4px;cursor:pointer;font-size:12px;margin-top:8px;">一括削除</button>';

      // Batch status change
      var batchBtnEls = propsEl.querySelectorAll('.batch-status-btn');
      for (var bbi = 0; bbi < batchBtnEls.length; bbi++) {
        (function(btn) {
          btn.addEventListener('click', function() {
            window.MA.history.pushHistory();
            var statusVal = btn.getAttribute('data-status');
            // ループの中では結果を積み上げる。毎回 ctx.getMmdText() から読み直すと
            // 最後の1件しか残らない (移設作業で実際にそうなった)。
            var _t4 = ctx.getMmdText();
            for (var bti = 0; bti < selectedTasks.length; bti++) {
              _t4 = updateTaskField(_t4, selectedTasks[bti].line, 'status', statusVal);
            }
            ctx.setMmdText(_t4);
            ctx.onUpdate();
          });
        })(batchBtnEls[bbi]);
      }

      // Batch date shift
      var shiftBtn = document.getElementById('batch-shift-btn');
      if (shiftBtn) {
        shiftBtn.addEventListener('click', function() {
          var daysVal = parseInt(document.getElementById('batch-shift-days').value, 10);
          if (isNaN(daysVal) || daysVal === 0) return;
          window.MA.history.pushHistory();
          var _t5 = ctx.getMmdText();
          for (var sti = 0; sti < selectedTasks.length; sti++) {
            var st = selectedTasks[sti];
            var newStart = st.startDate && DATE_RE.test(st.startDate) ? window.MA.dateUtils.addDays(st.startDate, daysVal) : null;
            var newEnd = st.endDate && DATE_RE.test(st.endDate) ? window.MA.dateUtils.addDays(st.endDate, daysVal) : null;
            if (newStart || newEnd) {
              _t5 = updateTaskDates(_t5, st.line, newStart, newEnd);
            }
          }
          ctx.setMmdText(_t5);
          ctx.onUpdate();
        });
      }

      // Batch delete (reverse line order to preserve line numbers)
      var batchDelBtn = document.getElementById('batch-delete-btn');
      if (batchDelBtn) {
        batchDelBtn.addEventListener('click', function() {
          window.MA.history.pushHistory();
          // Sort by line number descending so deletion doesn't shift lines
          var sorted = selectedTasks.slice().sort(function(a, b) { return b.line - a.line; });
          // 同上。行番号の大きい方から消すので、積み上げても行がずれない。
          var _t6 = ctx.getMmdText();
          for (var di = 0; di < sorted.length; di++) {
            _t6 = deleteTask(_t6, sorted[di].line);
          }
          ctx.setMmdText(_t6);
          window.MA.selection.setSelected([]);
          ctx.onUpdate();
        });
      }
      return;
    }

    // Section selected
    if (selData.length === 1 && selData[0].type === 'section') {
      var secId = selData[0].id;
      var section = null;
      if (parsedData && parsedData.sections) {
        for (var sci = 0; sci < parsedData.sections.length; sci++) {
          if (parsedData.sections[sci].name === secId) {
            section = parsedData.sections[sci];
            break;
          }
        }
      }
      if (!section) {
        propsEl.innerHTML = '<p style="color:var(--text-secondary);font-size:11px;">セクションが見つかりません</p>';
        return;
      }

      // Tasks in this section
      var secTasks = [];
      if (parsedData && parsedData.tasks) {
        var secIndex = parsedData.sections.indexOf(section);
        for (var sti2 = 0; sti2 < parsedData.tasks.length; sti2++) {
          if (parsedData.tasks[sti2].sectionIndex === secIndex) {
            secTasks.push(parsedData.tasks[sti2]);
          }
        }
      }

      var taskList = secTasks.map(function(t) {
        return '<div style="padding:2px 4px;font-size:11px;color:var(--text-primary);">' + window.MA.htmlUtils.escHtml(t.label) + '</div>';
      }).join('');

      propsEl.innerHTML =
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:2px;">セクション名</label>' +
          '<input id="prop-sec-name" type="text" value="' + window.MA.htmlUtils.escHtml(section.name) + '" style="width:100%;background:var(--bg-tertiary);border:1px solid var(--border);color:var(--text-primary);padding:3px 6px;border-radius:3px;font-size:12px;">' +
        '</div>' +
        '<div style="margin-bottom:8px;">' +
          '<label style="display:block;font-size:10px;color:var(--text-secondary);margin-bottom:4px;">タスク一覧 (' + secTasks.length + '件)</label>' +
          taskList +
        '</div>' +
        '<button id="prop-sec-delete-btn" style="width:100%;background:var(--accent-red);color:#fff;border:none;padding:5px 8px;border-radius:4px;cursor:pointer;font-size:12px;margin-top:8px;">セクション削除 (タスクごと)</button>';

      // Bind section name change
      var secNameEl = document.getElementById('prop-sec-name');
      if (secNameEl) {
        secNameEl.addEventListener('change', function() {
          window.MA.history.pushHistory();
          var lines = ctx.getMmdText().split('\n');
          var idx = section.line - 1;
          if (idx >= 0 && idx < lines.length) {
            var indent = lines[idx].match(/^(\s*)/)[1];
            lines[idx] = indent + 'section ' + secNameEl.value;
            var _t7 = lines.join('\n');
            ctx.setMmdText(_t7);
            window.MA.selection.setSelected([{ type: 'section', id: secNameEl.value }]);
            ctx.onUpdate();
          }
        });
      }

      // Bind section delete
      var secDelBtn = document.getElementById('prop-sec-delete-btn');
      if (secDelBtn) {
        secDelBtn.addEventListener('click', function() {
          window.MA.history.pushHistory();
          var _t8 = deleteSection(ctx.getMmdText(), section.line);
          ctx.setMmdText(_t8);
          window.MA.selection.setSelected([]);
          ctx.onUpdate();
        });
      }
      return;
    }

    // Default fallback
    propsEl.innerHTML = '<p style="color:var(--text-secondary);font-size:11px;">タスクを選択してください</p>';
  }

  return {
    type: 'gantt',
    displayName: 'Gantt',
    detect: function(text) { return text.trim().startsWith('gantt'); },
    parse: parseGantt,
    template: function() {
      return [
        'gantt',
        '    title プロジェクト計画',
        '    dateFormat YYYY-MM-DD',
        // axisFormat はあえて書かない。DSL の axisFormat 行は mermaid の
        // config より優先するので、ここで %m/%d を固定すると
        // チャートが伸びても年が出ない。実測で 3 年の計画に
        // 04/01 が 4 回、07/01 が 3 回並ぶ。app.js の ganttAxisFor に
        // 任せれば短い間は %m/%d、長くなれば %Y/%m に切り替わる。
        '',
        '    section 要件定義',
        '    要件分析           :a1, 2026-04-01, 2026-04-15',
      ].join('\n');
    },
    // Public API for use by app.js (until full DiagramModule v2 abstraction)
    parseGantt: parseGantt,
    parseTaskLine: parseTaskLine,
    rebuildTaskMeta: rebuildTaskMeta,
    updateTaskDates: updateTaskDates,
    updateTaskField: updateTaskField,
    addTask: addTask,
    nextTaskId: nextTaskId,
    nextStartDate: nextStartDate,
    nextDurationDays: nextDurationDays,
    milestoneMeta: milestoneMeta,
    deleteTask: deleteTask,
    sanitizeAfterDependencies: sanitizeAfterDependencies,
    addSection: addSection, moveSection: moveSection, resolveSpan: resolveSpan,
    deleteSection: deleteSection,
    updateGlobalSetting: updateGlobalSetting,
    removeGlobalSetting: removeGlobalSetting,
    moveTaskWithinSection: moveTaskWithinSection,
    moveTaskToSection: moveTaskToSection,
    buildOverlay: buildOverlay,
    renderProps: renderProps,
    addForm: addForm,
    setAddFormFocus: setAddFormFocus,
    resetTransientState: resetTransientState,
    calibrateScale: calibrateScale,
    isMilestoneRect: isMilestoneRect,
    pxToDate: pxToDate,
    dateToPx: dateToPx,
    getCalibration: function() { return calibration; },
    setCalibration: function(c) { calibration = c; },
    DATE_RE: DATE_RE,
    DURATION_RE: DURATION_RE,
    STATUS_KEYWORDS: STATUS_KEYWORDS,
  };
})();
